version: 2
machine:
  services:
    - docker

jobs:
  build:
    docker:
      - image: node:8.8.0@sha256:38fffe0479899db202a26b87da2a10e5be38e5525390f2c96820c058fbd177bc
      - image: mongo:3.4.4@sha256:c4bc4644b967a4b58022a79cf5c9afcd25ed08180c958a74df57b7753cfc8649
      - image: redis:3.2.7@sha256:afa4b429ef3ee08c8b198e50d684c5da0ffa43ae58631f61b08829bd6df3c500
    environment:
      - DOCKER_REPO_SLUG: learninglocker/xapi-service
      - DOCKER_USERNAME: ryansmith94
      - DOCKER_EMAIL: 0ryansmith1994@gmail.com
      - NPM_CONFIG_LOGLEVEL: warn
      - WINSTON_CONSOLE_LEVEL: none
      - EXPRESS_PORT: 1337
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Installing Dependencies
          command: yarn install --ignore-engines
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Compiling Code
          command: yarn build
      - run:
          name: Conformance Tests
          command: sh test.sh
      - run:
          name: Linting Code
          command: yarn lint -- -c tslint.ci.json
      - run:
          name: Docker Install
          command: |
            set -x
            DOCKER_VERSION="17.03.0-ce"
            curl -L -o /tmp/docker-$DOCKER_VERSION.tgz https://get.docker.com/builds/Linux/x86_64/docker-$DOCKER_VERSION.tgz
            tar -xz -C /tmp -f /tmp/docker-$DOCKER_VERSION.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Docker Build
          command: docker build -t "$DOCKER_REPO_SLUG" .
      - deploy:
          name: Semantic Release
          command: yarn semantic-release
