version: 2
machine:
  services:
    - mongodb
    - redis-server

jobs:
  build:
    docker:
      - image: node:8.8.0
      - image: mongo:3.4.4
      - image: redis:3.2.7
    environment:
      - DOCKER_REPO_SLUG: learninglocker/xapi-service
      - DOCKER_USERNAME: ryansmith94
      - NPM_CONFIG_LOGLEVEL: warn
      - WINSTON_CONSOLE_LEVEL: info
      - EXPRESS_PORT: 1337
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn build
      - run: sh test.sh
      - run: yarn lint -- -c tslint.ci.json
      - deploy:
          name: Semantic Release
          command: yarn semantic-release
      - deploy:
          name: Docker Push
          command: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push $DOCKER_REPO_SLUG:$CIRCLE_BRANCH
